services:
  - type: web
    name: flipcart_ecom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wecart.ecom.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: wecart.ecom.settings
      - key: PYTHON_VERSION
        value: 3.11.8
